from flask import Flask, render_template
import json
import os

app = Flask(__name__)

# Kho từ vựng mẫu (bạn có thể thêm thoải mái)
vocabulary = {
    "Test 1": [
  {"english":"take place","vietnamese":"diễn ra, xảy ra","explanation":"Dùng để nói một sự kiện diễn ra."},
  {"english":"attendee","vietnamese":"người tham dự","explanation":"Người tham gia một sự kiện."},
  {"english":"antique","vietnamese":"đồ cổ, cổ xưa","explanation":"Đồ vật có giá trị từ quá khứ."},
  {"english":"organization","vietnamese":"tổ chức, cơ quan","explanation":"Nhóm người có mục tiêu chung."},
  {"english":"suspicious","vietnamese":"đáng ngờ","explanation":"Gây nghi ngờ."},
  {"english":"vary","vietnamese":"thay đổi, khác nhau","explanation":"Không cố định, thay đổi."},
  {"english":"inventory","vietnamese":"hàng tồn kho","explanation":"Danh sách hàng hóa có sẵn."},
  {"english":"expand","vietnamese":"mở rộng","explanation":"Làm lớn hơn về quy mô."},
  {"english":"solicit","vietnamese":"kêu gọi","explanation":"Yêu cầu hoặc kêu gọi ai đó làm gì."},
  {"english":"intend","vietnamese":"dự định","explanation":"Có kế hoạch làm gì đó."},
  {"english":"prevent","vietnamese":"ngăn chặn","explanation":"Làm cho điều gì không xảy ra."},
  {"english":"aim","vietnamese":"mục tiêu","explanation":"Đích hướng tới."},
  {"english":"qualified","vietnamese":"đủ điều kiện","explanation":"Có khả năng hoặc bằng cấp."},
  {"english":"resident","vietnamese":"cư dân","explanation":"Người sống tại một nơi."},
  {"english":"agreement","vietnamese":"hợp đồng","explanation":"Sự thỏa thuận giữa các bên."},
  {"english":"opposition","vietnamese":"sự đối lập","explanation":"Sự phản đối."},
  {"english":"extensive","vietnamese":"sâu rộng","explanation":"Có phạm vi lớn."},
  {"english":"guarantee","vietnamese":"đảm bảo","explanation":"Cam kết chắc chắn."},
  {"english":"supplier","vietnamese":"nhà cung cấp","explanation":"Cung cấp hàng hóa."},
  {"english":"landscaping","vietnamese":"thiết kế cảnh quan","explanation":"Trang trí không gian ngoài trời."},
  {"english":"suggestion","vietnamese":"gợi ý","explanation":"Ý kiến đề xuất."},
  {"english":"expertise","vietnamese":"chuyên môn","explanation":"Kỹ năng chuyên sâu."},
  {"english":"competitor","vietnamese":"đối thủ","explanation":"Người cạnh tranh."},
  {"english":"anniversary","vietnamese":"kỷ niệm","explanation":"Ngày kỷ niệm."},
  {"english":"dedication","vietnamese":"sự cống hiến","explanation":"Tinh thần tận tâm."},
  {"english":"loyalty","vietnamese":"lòng trung thành","explanation":"Sự gắn bó lâu dài."},
  {"english":"contribute","vietnamese":"đóng góp","explanation":"Góp phần vào."},
  {"english":"gratitude","vietnamese":"lòng biết ơn","explanation":"Sự cảm kích."},
  {"english":"refine","vietnamese":"tinh chỉnh","explanation":"Cải thiện chi tiết."},
  {"english":"spacious","vietnamese":"rộng rãi","explanation":"Có nhiều không gian."},
  {"english":"go through","vietnamese":"trải qua","explanation":"Kinh qua điều gì đó."},
  {"english":"various","vietnamese":"đa dạng","explanation":"Nhiều loại khác nhau."},
  {"english":"secure","vietnamese":"an toàn","explanation":"Được bảo vệ chắc chắn."},
  {"english":"remove","vietnamese":"loại bỏ","explanation":"Lấy đi."},
  {"english":"previous","vietnamese":"trước đó","explanation":"Xảy ra trước."},
  {"english":"cooperation","vietnamese":"hợp tác","explanation":"Làm việc cùng nhau."},
  {"english":"upcoming","vietnamese":"sắp tới","explanation":"Sắp xảy ra."},
  {"english":"charge","vietnamese":"tính phí","explanation":"Thu tiền."},
  {"english":"assign","vietnamese":"phân công","explanation":"Giao nhiệm vụ."},
  {"english":"administrator","vietnamese":"quản trị viên","explanation":"Người quản lý hệ thống."},
  {"english":"new hire","vietnamese":"nhân viên mới","explanation":"Người mới được tuyển."},
  {"english":"promote","vietnamese":"thăng chức","explanation":"Nâng cấp vị trí."},
  {"english":"advertise","vietnamese":"quảng cáo","explanation":"Giới thiệu sản phẩm."},
  {"english":"coordinator","vietnamese":"điều phối viên","explanation":"Người sắp xếp công việc."},
  {"english":"telescope","vietnamese":"kính thiên văn","explanation":"Dụng cụ quan sát xa."},
  {"english":"revise","vietnamese":"chỉnh sửa","explanation":"Xem lại và sửa."},
  {"english":"representative","vietnamese":"đại diện","explanation":"Người thay mặt."},
  {"english":"inquiry","vietnamese":"yêu cầu, thắc mắc","explanation":"Câu hỏi cần giải đáp."},
  {"english":"general","vietnamese":"chung","explanation":"Không cụ thể."},
  {"english":"release","vietnamese":"phát hành","explanation":"Đưa ra công chúng."},
  {"english":"indicate","vietnamese":"chỉ ra","explanation":"Cho thấy."},
  {"english":"retain","vietnamese":"giữ lại","explanation":"Không mất đi."},
  {"english":"flavour","vietnamese":"hương vị","explanation":"Vị của thức ăn."},
  {"english":"sacrifice","vietnamese":"hy sinh","explanation":"Từ bỏ vì mục tiêu lớn hơn."},
  {"english":"obtain","vietnamese":"đạt được","explanation":"Có được."},
  {"english":"merger","vietnamese":"sáp nhập","explanation":"Kết hợp công ty."},
  {"english":"nutritious","vietnamese":"bổ dưỡng","explanation":"Tốt cho sức khỏe."},
  {"english":"individual","vietnamese":"cá nhân","explanation":"Một người riêng lẻ."},
  {"english":"opportunity","vietnamese":"cơ hội","explanation":"Khả năng đạt được điều gì."},
  {"english":"substitute","vietnamese":"thay thế","explanation":"Dùng cái khác thay."},
  {"english":"critical","vietnamese":"quan trọng","explanation":"Mang tính quyết định."},
  {"english":"colleague","vietnamese":"đồng nghiệp","explanation":"Người làm cùng."},
  {"english":"courtesy","vietnamese":"lịch sự","explanation":"Thái độ nhã nhặn."},
  {"english":"get the word out","vietnamese":"truyền thông tin","explanation":"Lan truyền thông tin."},
  {"english":"install","vietnamese":"cài đặt","explanation":"Thiết lập hệ thống."},
  {"english":"significant","vietnamese":"quan trọng","explanation":"Có ý nghĩa lớn."},
  {"english":"estimate","vietnamese":"ước tính","explanation":"Đoán gần đúng."},
  {"english":"liaison","vietnamese":"liên lạc","explanation":"Kết nối giữa các bên."},
  {"english":"successive","vietnamese":"liên tiếp","explanation":"Xảy ra nối tiếp."},
  {"english":"expert","vietnamese":"chuyên gia","explanation":"Người giỏi lĩnh vực."},
  {"english":"diagnose","vietnamese":"chẩn đoán","explanation":"Xác định bệnh/vấn đề."},
  {"english":"replace","vietnamese":"thay thế","explanation":"Đổi cái mới."},
  {"english":"resemble","vietnamese":"giống","explanation":"Có nét tương tự."},
  {"english":"approve","vietnamese":"phê duyệt","explanation":"Chấp nhận chính thức."},
  {"english":"inspection","vietnamese":"kiểm tra","explanation":"Xem xét kỹ."},
  {"english":"proactive","vietnamese":"chủ động","explanation":"Tự giác hành động."},
  {"english":"procedure","vietnamese":"quy trình","explanation":"Các bước thực hiện."},
  {"english":"compete","vietnamese":"cạnh tranh","explanation":"Thi đấu với nhau."},
  {"english":"instrumental","vietnamese":"quan trọng","explanation":"Đóng vai trò then chốt."},
  {"english":"combine","vietnamese":"kết hợp","explanation":"Gộp nhiều yếu tố lại với nhau thành một."}
],
    "Test 2": [
  {"english":"reliability","vietnamese":"sự đáng tin cậy","explanation":"Mức độ có thể tin tưởng."},
  {"english":"reimbursement","vietnamese":"sự hoàn tiền","explanation":"Việc trả lại chi phí đã chi."},
  {"english":"accept","vietnamese":"chấp nhận","explanation":"Đồng ý nhận."},
  {"english":"candidate","vietnamese":"ứng viên","explanation":"Người tham gia ứng tuyển."},
  {"english":"master","vietnamese":"nắm vững","explanation":"Thành thạo một kỹ năng."},
  {"english":"power failure","vietnamese":"mất điện","explanation":"Sự cố điện bị ngắt."},
  {"english":"property","vietnamese":"tài sản","explanation":"Vật sở hữu có giá trị."},
  {"english":"strategy","vietnamese":"chiến lược","explanation":"Kế hoạch dài hạn."},
  {"english":"name","vietnamese":"bổ nhiệm","explanation":"Chỉ định vào vị trí."},
  {"english":"warranty","vietnamese":"bảo hành","explanation":"Cam kết sửa chữa."},
  {"english":"workplace","vietnamese":"nơi làm việc","explanation":"Địa điểm làm việc."},
  {"english":"postpone","vietnamese":"trì hoãn","explanation":"Dời lại thời gian."},
  {"english":"struggle","vietnamese":"vật lộn","explanation":"Cố gắng vượt khó."},
  {"english":"ingredient","vietnamese":"thành phần","explanation":"Phần cấu tạo nên món ăn."},
  {"english":"savory","vietnamese":"mặn ngon","explanation":"Có vị mặn (không ngọt)."},
  {"english":"eager","vietnamese":"háo hức","explanation":"Rất mong chờ."},
  {"english":"artificial","vietnamese":"nhân tạo","explanation":"Không tự nhiên."},
  {"english":"substance","vietnamese":"chất","explanation":"Vật chất cụ thể."},
  {"english":"handy","vietnamese":"tiện lợi","explanation":"Dễ sử dụng."},
  {"english":"effective","vietnamese":"hiệu quả","explanation":"Mang lại kết quả tốt."},
  {"english":"sustainable","vietnamese":"bền vững","explanation":"Duy trì lâu dài."},
  {"english":"address","vietnamese":"giải quyết","explanation":"Xử lý vấn đề."},
  {"english":"porous","vietnamese":"xốp","explanation":"Có nhiều lỗ nhỏ."},
  {"english":"subscription","vietnamese":"đăng ký","explanation":"Trả tiền định kỳ."},
  {"english":"access","vietnamese":"truy cập","explanation":"Có quyền vào."},
  {"english":"valid","vietnamese":"hợp lệ","explanation":"Có giá trị pháp lý."},
  {"english":"expire","vietnamese":"hết hạn","explanation":"Không còn hiệu lực."},
  {"english":"activate","vietnamese":"kích hoạt","explanation":"Làm cho hoạt động."},
  {"english":"distribute","vietnamese":"phân phối","explanation":"Chia và phát đi."},
  {"english":"feature","vietnamese":"tính năng","explanation":"Đặc điểm nổi bật."},
  {"english":"reveal","vietnamese":"tiết lộ","explanation":"Làm lộ ra."},
  {"english":"extension","vietnamese":"gia hạn","explanation":"Kéo dài thêm."},
  {"english":"complaint","vietnamese":"khiếu nại","explanation":"Phản ánh không hài lòng."},
  {"english":"issue","vietnamese":"vấn đề","explanation":"Điều cần giải quyết."},
  {"english":"maintenance","vietnamese":"bảo trì","explanation":"Giữ cho hoạt động tốt."},
  {"english":"summarize","vietnamese":"tóm tắt","explanation":"Rút gọn nội dung."},
  {"english":"notify","vietnamese":"thông báo","explanation":"Cho biết thông tin."},
  {"english":"requirement","vietnamese":"yêu cầu","explanation":"Điều cần thiết."},
  {"english":"freight","vietnamese":"hàng hóa","explanation":"Hàng vận chuyển."},
  {"english":"vehicle","vietnamese":"phương tiện","explanation":"Dùng để di chuyển."},
  {"english":"transport","vietnamese":"vận chuyển","explanation":"Di chuyển hàng/người."},
  {"english":"nationwide","vietnamese":"toàn quốc","explanation":"Trên cả nước."},
  {"english":"executive","vietnamese":"giám đốc","explanation":"Người điều hành cấp cao."},
  {"english":"commercial","vietnamese":"thương mại","explanation":"Liên quan kinh doanh."},
  {"english":"demand","vietnamese":"nhu cầu","explanation":"Sự cần thiết."},
  {"english":"specialty","vietnamese":"đặc sản","explanation":"Món đặc trưng."},
  {"english":"convert","vietnamese":"chuyển đổi","explanation":"Biến từ dạng này sang dạng khác."},
  {"english":"virtual","vietnamese":"ảo","explanation":"Tồn tại trên máy tính."},
  {"english":"visualization","vietnamese":"trực quan hóa","explanation":"Biểu diễn bằng hình ảnh."},
  {"english":"suggest","vietnamese":"gợi ý","explanation":"Đưa ra đề xuất."},
  {"english":"curate","vietnamese":"tuyển chọn","explanation":"Chọn lọc nội dung."},
  {"english":"highlight","vietnamese":"làm nổi bật","explanation":"Nhấn mạnh."},
  {"english":"process","vietnamese":"quy trình","explanation":"Chuỗi bước thực hiện."},
  {"english":"sleek","vietnamese":"bóng mượt","explanation":"Kiểu dáng đẹp."},
  {"english":"stabilization","vietnamese":"ổn định hóa","explanation":"Làm ổn định."},
  {"english":"rough","vietnamese":"thô ráp","explanation":"Không mịn."},
  {"english":"surface","vietnamese":"bề mặt","explanation":"Phần ngoài."},
  {"english":"discontinue","vietnamese":"ngừng","explanation":"Dừng sản xuất."},
  {"english":"instruction","vietnamese":"hướng dẫn","explanation":"Chỉ dẫn cách làm."},
  {"english":"residence","vietnamese":"nơi ở","explanation":"Chỗ sinh sống."},
  {"english":"complimentary","vietnamese":"miễn phí","explanation":"Không mất tiền."},
  {"english":"accommodate","vietnamese":"cung cấp chỗ","explanation":"Đáp ứng nhu cầu."},
  {"english":"catch up","vietnamese":"bắt kịp","explanation":"Theo kịp tiến độ."},
  {"english":"customized","vietnamese":"tùy chỉnh","explanation":"Làm theo yêu cầu."},
  {"english":"express","vietnamese":"nhanh","explanation":"Tốc độ cao."},
  {"english":"preserve","vietnamese":"bảo tồn","explanation":"Giữ nguyên trạng."},
  {"english":"auction","vietnamese":"đấu giá","explanation":"Bán bằng trả giá."},
  {"english":"donate","vietnamese":"quyên góp","explanation":"Cho tặng."},
  {"english":"operation","vietnamese":"hoạt động","explanation":"Quá trình vận hành."},
  {"english":"thrilled","vietnamese":"phấn khích","explanation":"Rất vui."},
  {"english":"in advance","vietnamese":"trước","explanation":"Trước thời điểm."},
  {"english":"indeed","vietnamese":"thật sự","explanation":"Nhấn mạnh."},
  {"english":"typically","vietnamese":"thường","explanation":"Xảy ra phổ biến."},
  {"english":"smudge","vietnamese":"vết bẩn","explanation":"Vết lem."},
  {"english":"found","vietnamese":"thành lập","explanation":"Tạo ra tổ chức."},
  {"english":"emphasize","vietnamese":"nhấn mạnh","explanation":"Làm nổi bật."},
  {"english":"immediately","vietnamese":"ngay lập tức","explanation":"Không chậm trễ."},
  {"english":"average","vietnamese":"trung bình","explanation":"Giá trị giữa."},
  {"english":"navigate","vietnamese":"điều hướng","explanation":"Dẫn đường."},
  {"english":"ultimately","vietnamese":"cuối cùng","explanation":"Kết quả sau cùng."}
],
    "Test 3":[
  {"english":"youth","vietnamese":"tuổi trẻ, giới trẻ","explanation":"Giai đoạn trẻ tuổi hoặc nhóm người trẻ."},
  {"english":"conduct","vietnamese":"tiến hành, thực hiện / hành kiểm","explanation":"Thực hiện hành động hoặc cách cư xử."},
  {"english":"regular","vietnamese":"thường xuyên, đều đặn","explanation":"Xảy ra lặp lại theo chu kỳ."},
  {"english":"a majority of","vietnamese":"đa số, phần lớn","explanation":"Hơn một nửa số lượng."},
  {"english":"represent","vietnamese":"đại diện","explanation":"Thay mặt cho ai đó."},
  {"english":"measure","vietnamese":"đo lường / biện pháp","explanation":"Đánh giá hoặc cách giải quyết."},
  {"english":"submit","vietnamese":"nộp, đệ trình (tài liệu)","explanation":"Gửi chính thức."},
  {"english":"track","vietnamese":"theo dõi / đường ray, dấu vết","explanation":"Quan sát tiến trình hoặc dấu hiệu."},
  {"english":"rapidly","vietnamese":"một cách nhanh chóng","explanation":"Xảy ra rất nhanh."},
  {"english":"committee","vietnamese":"ủy ban, hội đồng","explanation":"Nhóm người ra quyết định."},
  {"english":"appendix","vietnamese":"phụ lục (sách, hợp đồng)","explanation":"Phần bổ sung cuối tài liệu."},
  {"english":"insight","vietnamese":"sự thấu hiểu, cái nhìn sâu sắc (dữ liệu)","explanation":"Hiểu rõ bản chất vấn đề."},
  {"english":"investment","vietnamese":"khoản đầu tư, sự đầu tư","explanation":"Bỏ tiền/tài nguyên để sinh lợi."},
  {"english":"result","vietnamese":"kết quả / dẫn đến","explanation":"Kết thúc hoặc hậu quả."},
  {"english":"improve","vietnamese":"cải thiện, nâng cao","explanation":"Làm tốt hơn."},
  {"english":"appoint","vietnamese":"bổ nhiệm","explanation":"Chỉ định vị trí."},
  {"english":"simultaneously","vietnamese":"đồng thời, cùng lúc","explanation":"Xảy ra cùng thời điểm."},
  {"english":"revenue","vietnamese":"doanh thu","explanation":"Tiền thu vào."},
  {"english":"undergo","vietnamese":"trải qua (thường là quy trình, khó khăn)","explanation":"Kinh qua một quá trình."},
  {"english":"take advantage","vietnamese":"tận dụng, lợi dụng","explanation":"Sử dụng cơ hội."},
  {"english":"transaction","vietnamese":"giao dịch","explanation":"Hoạt động mua bán."},
  {"english":"potential","vietnamese":"tiềm năng","explanation":"Khả năng phát triển."},
  {"english":"attention","vietnamese":"sự chú ý","explanation":"Tập trung vào."},
  {"english":"dynamic","vietnamese":"năng động","explanation":"Tràn đầy năng lượng."},
  {"english":"valuable","vietnamese":"có giá trị, quý giá","explanation":"Đáng giá hoặc hữu ích."},
  {"english":"convince","vietnamese":"thuyết phục","explanation":"Làm người khác tin."},
  {"english":"audience","vietnamese":"khán giả, thính giả","explanation":"Người xem/nghe."},
  {"english":"acquire","vietnamese":"đạt được, thâu tóm (mua lại công ty)","explanation":"Có được hoặc mua lại."},
  {"english":"share","vietnamese":"chia sẻ / cổ phần, cổ phiếu","explanation":"Phân chia hoặc phần sở hữu."},
  {"english":"strength","vietnamese":"thế mạnh, sức mạnh","explanation":"Điểm mạnh."},
  {"english":"quote","vietnamese":"báo giá / trích dẫn","explanation":"Đưa giá hoặc dẫn lời."},
  {"english":"infusion","vietnamese":"sự truyền vào (vốn), pha chế (trà)","explanation":"Đưa chất vào hoặc pha."},
  {"english":"refrain","vietnamese":"kiềm chế, tránh làm gì (refrain from)","explanation":"Không làm điều gì đó."},
  {"english":"preference","vietnamese":"sự ưu tiên, sở thích","explanation":"Thích hơn cái khác."},
  {"english":"function","vietnamese":"chức năng, buổi họp mặt / hoạt động","explanation":"Vai trò hoặc sự kiện."},
  {"english":"gathering","vietnamese":"cuộc họp mặt, sự tụ tập","explanation":"Tập hợp nhiều người."},
  {"english":"innovation","vietnamese":"sự đổi mới, sáng tạo","explanation":"Ý tưởng mới."},
  {"english":"shareholder","vietnamese":"cổ đông","explanation":"Người sở hữu cổ phần."},
  {"english":"productivity","vietnamese":"năng suất","explanation":"Hiệu suất làm việc."},
  {"english":"occur","vietnamese":"xảy ra, xuất hiện","explanation":"Diễn ra."},
  {"english":"optimize","vietnamese":"tối ưu hóa","explanation":"Làm tốt nhất có thể."},
  {"english":"conventional","vietnamese":"thông thường, theo tập quán, truyền thống","explanation":"Theo cách phổ biến."},
  {"english":"commuter","vietnamese":"người đi làm (phải di chuyển xa hàng ngày)","explanation":"Người đi làm xa."},
  {"english":"relieved","vietnamese":"cảm thấy nhẹ nhõm, an tâm","explanation":"Hết lo lắng."},
  {"english":"desperate","vietnamese":"tuyệt vọng, khao khát dữ dội","explanation":"Cảm xúc mạnh mẽ tiêu cực hoặc rất cần."},
  {"english":"municipal","vietnamese":"thuộc về thành phố, đô thị","explanation":"Liên quan chính quyền địa phương."},
  {"english":"entrance","vietnamese":"lối vào, cổng vào","explanation":"Nơi đi vào."},
  {"english":"mural","vietnamese":"tranh vẽ trên tường (tranh bích họa)","explanation":"Tranh lớn trên tường."},
  {"english":"commission","vietnamese":"tiền hoa hồng, ủy ban / ủy nhiệm","explanation":"Tiền thưởng bán hàng hoặc nhóm/việc giao."},
  {"english":"approximately","vietnamese":"xấp xỉ, khoảng","explanation":"Gần đúng."},
  {"english":"publicize","vietnamese":"công khai, quảng bá","explanation":"Làm cho nhiều người biết."},
  {"english":"significance","vietnamese":"tầm quan trọng, ý nghĩa","explanation":"Mức độ quan trọng."},
  {"english":"official","vietnamese":"chính thức / quan chức","explanation":"Được công nhận hoặc người chức vụ."},
  {"english":"mingle","vietnamese":"hòa nhập, trộn lẫn (giao lưu trong tiệc)","explanation":"Giao tiếp xã hội."},
  {"english":"invaluable","vietnamese":"vô giá (rất quý báu)","explanation":"Cực kỳ có giá trị."},
  {"english":"accurate","vietnamese":"chính xác","explanation":"Không sai lệch."},
  {"english":"recruit","vietnamese":"tuyển dụng / nhân viên mới","explanation":"Thu hút người mới."},
  {"english":"celebrity","vietnamese":"người nổi tiếng","explanation":"Người được nhiều người biết."},
  {"english":"cater","vietnamese":"phục vụ ăn uống (cater for), đáp ứng","explanation":"Cung cấp dịch vụ."},
  {"english":"equipment","vietnamese":"trang thiết bị (danh từ không đếm được)","explanation":"Dụng cụ cần thiết."},
  {"english":"distributor","vietnamese":"nhà phân phối","explanation":"Người phân phối hàng."},
  {"english":"component","vietnamese":"thành phần, linh kiện","explanation":"Phần cấu tạo."},
  {"english":"facility","vietnamese":"cơ sở vật chất (nhà máy, tòa nhà...)","explanation":"Nơi phục vụ hoạt động."},
  {"english":"assembly","vietnamese":"sự lắp ráp, hội đồng","explanation":"Quá trình lắp hoặc nhóm người."},
  {"english":"launch","vietnamese":"ra mắt, khởi động, phóng","explanation":"Bắt đầu sản phẩm/sự kiện."},
  {"english":"financial","vietnamese":"thuộc về tài chính","explanation":"Liên quan tiền bạc."},
  {"english":"oversee","vietnamese":"giám sát, trông coi","explanation":"Quản lý công việc."},
  {"english":"permanently","vietnamese":"vĩnh viễn, lâu dài","explanation":"Không thay đổi."},
  {"english":"relocate","vietnamese":"di dời, chuyển địa điểm","explanation":"Chuyển nơi ở/làm việc."},
  {"english":"appreciate","vietnamese":"cảm kích, đánh giá cao, tăng giá trị","explanation":"Biết ơn hoặc tăng giá."},
  {"english":"perspective","vietnamese":"quan điểm, góc nhìn","explanation":"Cách nhìn nhận."},
  {"english":"intrigue","vietnamese":"gây tò mò, hấp dẫn","explanation":"Kích thích sự tò mò."},
  {"english":"government","vietnamese":"chính phủ","explanation":"Cơ quan điều hành quốc gia."},
  {"english":"collaborate","vietnamese":"hợp tác","explanation":"Làm việc chung."},
  {"english":"commensurate","vietnamese":"tương xứng (với cái gì đó)","explanation":"Phù hợp về mức độ."},
  {"english":"comply with","vietnamese":"tuân thủ (luật, quy định)","explanation":"Làm theo quy định."},
  {"english":"essential","vietnamese":"thiết yếu, cốt yếu","explanation":"Rất cần thiết."},
  {"english":"relevant","vietnamese":"liên quan, thích hợp","explanation":"Có liên quan trực tiếp."},
  {"english":"formal","vietnamese":"trang trọng, chính quy","explanation":"Theo nghi thức."},
  {"english":"remote","vietnamese":"từ xa, hẻo lánh","explanation":"Xa xôi hoặc làm việc từ xa."}
]
}

@app.route('/')
def index():
    # Chuyển dữ liệu sang JSON để JS sử dụng
    return render_template('index.html', vocabulary=json.dumps(vocabulary))
if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))
    app.run(host='0.0.0.0', port=port)